[package]
name = "webpki-roots"
version = "0.13.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
readme = "README.md"
license = "MPL-2.0"
description = "Mozilla's CA root certificates for use with webpki"
homepage = "https://github.com/ctz/webpki-roots"
repository = "https://github.com/ctz/webpki-roots"

[dependencies]
untrusted = "0.5.1"
webpki = { git = "https://github.com/briansmith/webpki" }
